version: "2"
services:
  db:
    ports:
      - "5432:5432"
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=instameals

  web:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db