from .apps import (
    INSTALLED_APPS,
)
from .auth import (
    AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL,
    AUTHENTICATION_BACKENDS,
)
from .base import (
    ALLOWED_HOSTS,
    BASE_DIR,
    DATABASES,
    ROOT_URLCONF,
    SECRET_KEY,
    WSGI_APPLICATION,
)
from .internationalization import (
    LANGUAGE_CODE,
    TIME_ZONE,
    USE_I18N,
    USE_L10N,
    USE_TZ,
)
from .middleware import (
    MIDDLEWARE_CLASSES,
)
from .rest_framework import (
    REST_FRAMEWORK,
)
from .social_auth import (
    PROPRIETARY_BACKEND_NAME,
    SOCIAL_AUTH_FACEBOOK_KEY,
    SOCIAL_AUTH_FACEBOOK_SCOPE,
    SOCIAL_AUTH_FACEBOOK_SECRET,
    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
    SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE,
    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,
)
from .static_files import (
    STATIC_ROOT,
    STATIC_URL,
    STATICFILES_DIRS,
)
from .templates import (
    TEMPLATES,
)

__all__ = (
    'ALLOWED_HOSTS',
    'AUTH_PASSWORD_VALIDATORS',
    'AUTH_USER_MODEL',
    'AUTHENTICATION_BACKENDS',
    'BASE_DIR',
    'DATABASES',
    'INSTALLED_APPS',
    'LANGUAGE_CODE',
    'MIDDLEWARE_CLASSES',
    'PROPRIETARY_BACKEND_NAME',
    'REST_FRAMEWORK',
    'ROOT_URLCONF',
    'SECRET_KEY',
    'SOCIAL_AUTH_FACEBOOK_KEY',
    'SOCIAL_AUTH_FACEBOOK_SCOPE',
    'SOCIAL_AUTH_FACEBOOK_SECRET',
    'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY',
    'SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE',
    'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET',
    'STATIC_ROOT',
    'STATIC_URL',
    'STATICFILES_DIRS',
    'TEMPLATES',
    'TIME_ZONE',
    'USE_I18N',
    'USE_L10N',
    'USE_TZ',
    'WSGI_APPLICATION',
)
