# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
