# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 17:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default='Point(-84.51, 39.10)', srid=4326),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
