# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('view_address', 'View Address'),)},
        ),
        migrations.AlterModelOptions(
            name='allergen',
            options={'permissions': (('view_allergen', 'View Allergen'),)},
        ),
        migrations.AlterModelOptions(
            name='apiuser',
            options={'permissions': (('view_api_user', 'View APIUser'),)},
        ),
        migrations.AlterModelOptions(
            name='favoriteseller',
            options={'permissions': (('view_favorite_seller', 'View Favorite Seller'),)},
        ),
        migrations.AlterModelOptions(
            name='mealreview',
            options={'permissions': (('view_meal_review', 'View Meal Review'),)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_order', 'View Order'),)},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'permissions': (('view_order_review', 'View Order Review'),)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('view_rating', 'View Rating'),)},
        ),
        migrations.AlterModelOptions(
            name='sellerreview',
            options={'permissions': (('view_seller_review', 'View Seller Review'),)},
        ),
    ]
