# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0002_auto_20160409_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.TextField(choices=[('meal_image', 'meal_image'), ('profile_image', 'profile_image'), ('review_meal_image', 'review_meal_image'), ('other', 'other')], default='other'),
        ),
    ]
