# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0003_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='profile_image',
            field=models.OneToOneField(blank='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='instameals.Image'),
        ),
    ]
