# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0005_auto_20160411_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='meals', to='instameals.Image'),
        ),
    ]
