# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0007_auto_20160414_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cusine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
