# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0008_cusine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusine',
            new_name='Cuisine',
        ),
    ]
