# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0009_auto_20160426_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
