# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instameals', '0011_order_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
    ]
